# Generated by Django 5.0.3 on 2024-04-21 10:27

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='person',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(max_length=35)),
                ('last_name', models.CharField(max_length=40)),
                ('mail', models.CharField(max_length=50)),
                ('password', models.CharField(max_length=10)),
                ('isActive', models.BooleanField()),
            ],
        ),
    ]
