# Generated by Django 5.0.3 on 2024-04-23 13:41

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0002_comments'),
    ]

    operations = [
        migrations.AlterField(
            model_name='comments',
            name='dateTime',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
        migrations.AlterField(
            model_name='comments',
            name='isActive',
            field=models.BooleanField(default=True),
        ),
    ]
